### ISSUE TITLE
Container first time setup restarts continuously and can't connect to DB

### ISSUE THREAD

**Issue by gabeklavans** [papra-hq/papra#329]
### Describe the bug

Running this container for the first time on my system, I kept getting the following error and continual restarts in the container logs:

```
.env not found. Continuing without it.
.env not found. Continuing without it.
/app/node_modules/.pnpm/libsql@0.4.7/node_modules/libsql/index.js:83
      this.db = databaseOpen(path, authToken, encryptionCipher, encryptionKey);
                ^

Error: ConnectionFailed("Unable to open connection to local database ./app-data/db/db.sqlite: 14")
    at new Database (/app/node_modules/.pnpm/libsql@0.4.7/node_modules/libsql/index.js:83:17)
    at _createClient (file:///app/node_modules/.pnpm/@libsql+client@0.14.0/node_modules/@libsql/client/lib-esm/sqlite3.js:47:16)
    at _createClient (file:///app/node_modules/.pnpm/@libsql+client@0.14.0/node_modules/@libsql/client/lib-esm/node.js:21:16)
    at createClient (file:///app/node_modules/.pnpm/@libsql+client@0.14.0/node_modules/@libsql/client/lib-esm/node.js:11:12)
    at setupDatabase (/app/src/modules/app/database/database.ts:15:18)
    at <anonymous> (/app/src/scripts/commons/run-script.ts:26:30) {
  code: ''
}
```

I do use podman rootless with SELinux enabled but I believe I have all my permissions set up properly. This is evidenced by the fact that if I manually create this `db.sqlite` on the host system in the expected location in the volume mount, then container app setup proceeds seemingly successfully.

### What happened?

I expected to just run the basic docker compose provided by the documentation and have an auto-initialized papra setup.

### System information

```
OS: Fedora CoreOS 42.20250512.3.0 (uCore HCI) x86_64
Host: H110N
Kernel: Linux 6.14.5-300.fc42.x86_64
Shell: zsh 5.9
CPU: Intel(R) Core(TM) i5-6500 (4) @ 3.60 GHz
GPU: AMD Radeon RX 580 Series [Discrete]
Memory: 6.60 GiB / 31.29 GiB (21%)
```

my compose file:
```
services:
  papra:
    image: ghcr.io/papra-hq/papra:latest
    container_name: papra
    restart: unless-stopped
    ports:
      - 1221:1221
    environment:
      - AUTH_SECRET=$AUTH_SECRET
      - CLIENT_BASE_URL=<>
      - SERVER_BASE_URL=<>
      - INGESTION_FOLDER_IS_ENABLED=true
    volumes:
      - ~/elysium/appdata/papra/data:/app/app-data:Z
      - ~/tartarus/documents/ingestion:/app/ingestion:z
    user: 0:0 # simplify user namespace permissions, but I also tried mapped to my host ID with 1000:1000
```

### Where did you encounter the bug?

A self hosted instance

**Comment by CorentinTh** [comment]
Hi @gabeklavans 
It looks like some permition issues, was the `~/elysium/appdata/papra/data/db` folder been created and the db inside is read/writable to the binded user ?

The app will try to create the db folder path if it does not exists, and the sqlite file will be created by the libsql driver

**Comment by firestrife23** [comment]
@CorentinTh Same thing happened to me after copying and deploying the content from your Doc's docker-compose.yml generator. I verified the permission is not the issue, then I created the "db" folder within app-data folder and it just worked.

**Comment by gabeklavans** [comment]
> Hi [@gabeklavans](https://github.com/gabeklavans) It looks like some permition issues, was the `~/elysium/appdata/papra/data/db` folder been created and the db inside is read/writable to the binded user ?
> 
> The app will try to create the db folder path if it does not exists, and the sqlite file will be created by the libsql driver

I can be pretty certain it’s not a permission issue. I have permissions set up the same way with many other containers on my system, and once I manually created the db.sqlite, papra was able to write into it and create the original documents in the data folder once I started using it.

It’s possible there’s some sort of file creation permission distinct from a write permission? I’m not an expert on the matter, I’ve just done lots of trial and error lol

**Comment by CorentinTh** [comment]
I recently added a check to ensure the db directory exists (with auto creation) in #294 upon startup, but forgot that in the docker start command, the db migration are run before starting the app

I'll fix that, thank you for reporting!

**Comment by CorentinTh** [comment]
Fixed in #337 

- Try to create the missing database directories before running the migrations
- Added a troubleshooting page in the docs with a link to in the error message if the creation of the database directory fails
- Added a dynamic `docker compose up` command in the dc generator with subdirs creation

**Comment by excaliburzarau** [comment]
> Fixed in [#337](https://github.com/papra-hq/papra/pull/337)
> 
> * Try to create the missing database directories before running the migrations
> * Added a troubleshooting page in the docs with a link to in the error message if the creation of the database directory fails
> * Added a dynamic `docker compose up` command in the dc generator with subdirs creation

Hello @CorentinTh,

I am deploying the software on Docker Swarm. I am having this issue.

If i run it with the root image, it creates the database properly but, when using a rootless image, it does not work, it fails to create the database with the error above.

I ensured that the folders had 777 permission (to test) and the owner was the 1000:1000. It is still unable to create the database.

Would this be an expected limitation?

Best Regards

**Comment by gabeklavans** [comment]
> > Fixed in [#337](https://github.com/papra-hq/papra/pull/337)
> > 
> > * Try to create the missing database directories before running the migrations
> > * Added a troubleshooting page in the docs with a link to in the error message if the creation of the database directory fails
> > * Added a dynamic `docker compose up` command in the dc generator with subdirs creation
> 
> Hello [@CorentinTh](https://github.com/CorentinTh),
> 
> I am deploying the software on Docker Swarm. I am having this issue.
> 
> If i run it with the root image, it creates the database properly but, when using a rootless image, it does not work, it fails to create the database with the error above.
> 
> I ensured that the folders had 777 permission (to test) and the owner was the 1000:1000. It is still unable to create the database.
> 
> Would this be an expected limitation?
> 
> Best Regards

I’m pretty sure after the fix in this thread, I tested and observed the db being created in my rootless setup. But I’m not 100% certain, I may have just kept the existing db that I created.

**Comment by excaliburzarau** [comment]
> > > Fixed in [#337](https://github.com/papra-hq/papra/pull/337)
> > > 
> > > * Try to create the missing database directories before running the migrations
> > > * Added a troubleshooting page in the docs with a link to in the error message if the creation of the database directory fails
> > > * Added a dynamic `docker compose up` command in the dc generator with subdirs creation
> > 
> > 
> > Hello [@CorentinTh](https://github.com/CorentinTh),
> > I am deploying the software on Docker Swarm. I am having this issue.
> > If i run it with the root image, it creates the database properly but, when using a rootless image, it does not work, it fails to create the database with the error above.
> > I ensured that the folders had 777 permission (to test) and the owner was the 1000:1000. It is still unable to create the database.
> > Would this be an expected limitation?
> > Best Regards
> 
> I’m pretty sure after the fix in this thread, I tested and observed the db being created in my rootless setup. But I’m not 100% certain, I may have just kept the existing db that I created.

<img width="968" height="547" alt="Image" src="https://github.com/user-attachments/assets/c5f2c322-7528-4077-a2e6-17fffd97939e" />

Hello @gabeklavans,

Thank you for your help on this issue.

The image above is what is happening with the container and the folders permissions.

My docker compose for docker swarm has the following variables regarding permissions.

<img width="353" height="162" alt="Image" src="https://github.com/user-attachments/assets/5989528d-bf71-421b-ac64-20e76b9114cd" />

I am unsure if there is a limitation that might be occuring on this but it is failing to create the DB every time.

<img width="508" height="55" alt="Image" src="https://github.com/user-attachments/assets/611b94a8-22e1-41c9-9191-18dba8f2b4fd" />

These are my mounted bind volumes.

Best Regards

Note: I tried with the latest and older images.

**Comment by excaliburzarau** [comment]
Hello again,

I have now found the problem and resolved it.

After deploying the software on a Docker volume i realized that the folder db is being created with permissions 999 regardless of the permissions defined on the docker compose.

So i have changed the permissions of the db folder to 999 and the issue is now resolved.

Best Regards and thank you all.
